Repository near/wallet-selector, pull requests merged in 2021-12, with the labels that each got.

#32 task-31 hide custom path button
  src/components/Modal/Modal.styles.ts
  src/components/Modal/Modal.tsx
Labels: enhancement, task

#37 Task 34/restructure classes into multiple wallet types
  .vscode/settings.json
  src/config.ts
  src/constants.ts
  src/contracts/SmartContract.ts
  src/controllers/WalletController.ts
  src/core/Core.ts
  src/core/NearWalletSelector.ts
  src/index.ts
  src/interfaces/ILedgerWallet.ts
  src/interfaces/INearWallet.ts
  src/interfaces/INearWalletSelector.ts
  src/interfaces/ISenderWallet.ts
  src/interfaces/IWallet.ts
  src/modal/ModalHelper.tsx
  src/modal/component/Modal/Modal.styles.ts
  src/modal/component/Modal/Modal.tsx
  src/state/State.ts
  src/types/Options.ts
  src/types/State.ts
  src/utils/HelperFunctions.ts
  src/wallets/BaseWallet.ts
  src/wallets/CustomWallet.ts
  src/wallets/browser/NearWallet.ts
  src/wallets/default/NarWallet.ts
  src/wallets/default/NearWallet.ts
  src/wallets/hardware/LedgerWallet.ts
  src/wallets/index.ts
  src/wallets/injected/SenderWallet.ts
  src/wallets/types/BrowserWallet.ts
  src/wallets/types/HardwareWallet.ts
  src/wallets/types/InjectedWallet.ts
Labels: enhancement

#42 added collapsible wallet explanation
  .idea/.gitignore
  .idea/modules.xml
  .idea/prettier.xml
  .idea/vcs.xml
  .idea/wallet-selector.iml
  src/modal/component/Modal/Modal.styles.ts
  src/modal/component/Modal/Modal.tsx
Labels: task

#44 Optionally render wallet explanation and set default description
  package-lock.json
  src/modal/component/Modal/Modal.styles.ts
  src/modal/component/Modal/Modal.tsx
  src/state/State.ts
  src/types/Options.ts
Labels: task
