Repository near/wallet-selector, pull requests merged in 2022-03, with the labels that each got.

#176 Fix typescript missing dependency in Angular Example
  examples/angular/package.json
  examples/angular/yarn.lock
Labels: bug

#182 Fix UI text and border colors
  src/modal/Modal.styles.ts
Labels: bug

#187 Config file tests
  src/config.spec.ts
Labels: task

#199 test: Added createNearWallet setup and isAvailable test
  src/wallets/browser/NearWallet.spec.ts
Labels: task

#219 chore: Update angular example
  examples/angular/src/app/app.component.html
  examples/angular/src/app/app.component.ts
  examples/angular/src/app/components/content/content.component.html
  examples/angular/src/app/components/content/content.component.ts
  examples/angular/src/app/components/form/form.component.html
  examples/angular/src/app/components/form/form.component.ts
  examples/angular/src/app/interfaces/account.ts
  examples/angular/src/config.ts
Labels: enhancement
