Repository near/wallet-selector, pull requests merged in 2022-05, with the labels that each got.

#244 chore(ci): version bumping
  .github/workflows/bump-version.yml
  .github/workflows/dev-pr.yml
  .github/workflows/pr-actions.yaml
  .gitignore
  package.json
  packages/core/project.json
  packages/ledger/project.json
  packages/math-wallet/project.json
  packages/near-wallet/project.json
  packages/sender/project.json
  packages/wallet-connect/project.json
  yarn.lock
Labels: scope:ci

#286 fix: Changed response interface for rpcChanged
  packages/sender/src/lib/injected-sender.ts
  packages/sender/src/lib/sender.ts
Labels: task

#265 refactor: Created utils package
  package.json
  packages/core/src/index.ts
  packages/core/src/lib/wallet/transactions.spec.ts
  packages/core/src/lib/wallet/transactions.ts
  packages/ledger/src/lib/ledger.ts
  packages/math-wallet/src/lib/math-wallet.ts
  packages/near-wallet/src/lib/near-wallet.ts
  packages/sender/src/lib/sender.ts
  packages/wallet-utils/.babelrc
  packages/wallet-utils/.eslintrc.json
  packages/wallet-utils/README.md
  packages/wallet-utils/jest.config.js
  packages/wallet-utils/package.json
  packages/wallet-utils/project.json
  packages/wallet-utils/src/index.ts
  packages/wallet-utils/src/lib/create-action.ts
  packages/wallet-utils/src/lib/sign-transactions.ts
  packages/wallet-utils/src/lib/wallet-utils.spec.ts
  packages/wallet-utils/src/lib/wallet-utils.ts
  packages/wallet-utils/tsconfig.json
  packages/wallet-utils/tsconfig.lib.json
  packages/wallet-utils/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: task

#289 fix: Fixed network param in signTransactions method, remowed transactions.ts
  packages/core/src/lib/wallet/index.ts
  packages/core/src/lib/wallet/transactions.ts
  packages/ledger/src/lib/ledger.ts
  packages/math-wallet/src/lib/math-wallet.ts
  packages/wallet-utils/src/lib/create-action.ts
  packages/wallet-utils/src/lib/sign-transactions.ts
Labels: bug

#293 refactor: Removed all playwright dependencies, removed all folder and files ass…
  .github/workflows/pr-actions.yaml
  e2e/example.e2e.ts
  examples/angular-e2e/.eslintrc.json
  examples/angular-e2e/jest.config.js
  examples/angular-e2e/project.json
  examples/angular-e2e/src/app.spec.ts
  examples/angular-e2e/src/utils.ts
  examples/angular-e2e/tsconfig.e2e.json
  examples/angular-e2e/tsconfig.json
  examples/react-e2e/.eslintrc.json
  examples/react-e2e/jest.config.js
  examples/react-e2e/project.json
  examples/react-e2e/src/app.spec.ts
  examples/react-e2e/src/utils.ts
  examples/react-e2e/tsconfig.e2e.json
  examples/react-e2e/tsconfig.json
  package.json
  playwright.config.ts
  workspace.json
  yarn.lock
Labels: task

#305 test: Sqac 150 ledger wallet unit testing
  packages/core/src/lib/testUtils.ts
  packages/ledger/src/lib/ledger.spec.ts
Labels: task
