Repository near/wallet-selector, pull requests merged in 2022-02, with the labels that each got.

#92 Task 91/event emitter
  __tests__/example.spec.tsx
  src/controllers/WalletController.ts
  src/core/NearWalletSelector.tsx
  src/types/EventHandler.ts
  src/types/EventList.ts
  src/utils/EventHandler.ts
  src/utils/EventsHandler.ts
  src/utils/__tests__/EventEmitter.unit.ts
  src/wallets/BaseWallet.ts
  src/wallets/CustomWallet.ts
  src/wallets/browser/NearWallet.ts
  src/wallets/hardware/LedgerWallet.ts
  src/wallets/injected/SenderWallet.ts
  src/wallets/types/BrowserWallet.ts
  src/wallets/types/HardwareWallet.ts
  src/wallets/types/InjectedWallet.ts
Labels: enhancement

#113 Improve Network Changes in SenderWallet
  src/modal/Modal.tsx
  src/wallets/injected/SenderWallet.ts
Labels: task

#122 Handle account change in Sender Wallet
  example/src/App.js
  src/interfaces/InjectedSenderWallet.ts
  src/wallets/injected/SenderWallet.ts
Labels: task

#90 Branded and responsive styling
  src/modal/Modal.styles.ts
  src/modal/Modal.tsx
  src/wallets/browser/NearWallet.ts
  src/wallets/injected/SenderWallet.ts
Labels: task

#143 Resetting state after modal hide and ledger connect
  src/modal/Modal.tsx
Labels: bug
