Repository near/wallet-selector, pull requests merged in 2022-04, with the labels that each got.

#232 docs: Updated docs for wallets
  packages/ledger-wallet/README.md
  packages/math-wallet/README.md
  packages/near-wallet/README.md
  packages/sender-wallet/README.md
  packages/wallet-connect/README.md
Labels: documentation

#234 fix: Fix eslint for packages
  .eslintignore
Labels: bug

#225 test: Task 211/add unit tests for ledgerwallet
  packages/ledger/src/lib/ledger.spec.ts
  packages/ledger/src/lib/ledger.ts
Labels: task

#239 feat: Finished signAndSendTransactions method
  packages/math-wallet/src/lib/math-wallet.ts
Labels: task

#240 feat: [SQAC-104] Add Batch Transaction Support for Ledger
  packages/ledger/src/lib/ledger.ts
Labels: enhancement

#241 feat: Finished signAndSendTransactions method
  packages/wallet-connect/src/lib/wallet-connect.ts
Labels: task

#242 fix: [SQAC-117] Bug fix for 'signOut' method in Ledger
  packages/ledger/src/lib/ledger.ts
Labels: bug

#245 fix: Added near_signAndSendTransactions to jsonrpc list when signing in to…
  packages/wallet-connect/src/lib/wallet-connect.ts
Labels: bug

#246 fix: SQAC-119 Bug Fix for getAccounts in Math Wallet
  packages/math-wallet/src/lib/math-wallet.ts
Labels: bug

#247 fix: Fixed bug where error was not shown when connecting with ledger
  packages/core/src/lib/modal/Modal.tsx
Labels: bug

#255 fix: SQAC-122 Improve Sender Error when requestSignIn Fails
  packages/sender/src/lib/injected-sender.ts
  packages/sender/src/lib/sender.ts
Labels: bug

#256 feat: Removed account id requirement for ledger connecting
  packages/core/src/lib/WalletController.ts
  packages/core/src/lib/modal/Modal.tsx
  packages/core/src/lib/wallet/wallet.ts
  packages/ledger/src/lib/ledger.spec.ts
  packages/ledger/src/lib/ledger.ts
Labels: task

#262 feat: Resolved conflicts
  packages/core/src/lib/options.ts
  packages/core/src/lib/options.types.ts
  packages/core/src/lib/wallet-selector.ts
  packages/core/src/lib/wallet-selector.types.ts
Labels: task

#263 refactor: Sqac 111 improve routing logic within modal
  packages/core/src/lib/modal/components/LedgerDerivationPath.tsx
  packages/core/src/lib/modal/components/Modal.tsx
  packages/core/src/lib/modal/components/WalletNetworkChanged.tsx
  packages/core/src/lib/modal/components/WalletNotInstalled.tsx
  packages/core/src/lib/modal/components/WalletOptions.tsx
Labels: task

#268 feat: Disabled wallet option while connecting
  packages/core/src/lib/modal/components/Modal.styles.ts
  packages/core/src/lib/modal/components/WalletOptions.tsx
Labels: task

#267 fix: Fixed Sender Discconect bug
  packages/core/src/lib/modal/components/Modal.tsx
  packages/sender/src/lib/injected-sender.ts
  packages/sender/src/lib/sender.ts
Labels: bug, automerge

#269 chore: Close Modal by Pressing the ESC Key
  packages/core/src/lib/modal/components/Modal.tsx
Labels: enhancement, automerge

#270 feat: Replaced alert with custom modal
  packages/core/src/lib/modal/components/AlertModal.tsx
  packages/core/src/lib/modal/components/Modal.styles.ts
  packages/core/src/lib/modal/components/Modal.tsx
  packages/core/src/lib/modal/components/WalletOptions.tsx
Labels: task

#272 refactor: Modified isAvailable function to be async
  packages/core/src/lib/modal/components/WalletOptions.tsx
  packages/core/src/lib/wallet/wallet.ts
  packages/ledger/src/lib/ledger.spec.ts
  packages/ledger/src/lib/ledger.ts
  packages/math-wallet/src/lib/math-wallet.ts
  packages/near-wallet/src/lib/near-wallet.spec.ts
  packages/near-wallet/src/lib/near-wallet.ts
  packages/sender/src/lib/sender.ts
  packages/wallet-connect/src/lib/wallet-connect.ts
Labels: enhancement

#275 fix: Handle accountChanged for Sender
  packages/sender/src/lib/sender.ts
Labels: bug
